#
# print(f'\n\033[92m<<<=====================[ 正在拆分小分子输入文件 ]====================>>>\033[0m')
# print(f'\n\033[92m<<<============[ Splitting small molecule input file ]============>>>\033[0m')
# print(f'\n\033[92m<<<=======================[ 输入文件拆分完成 ]=======================>>>\033[0m')
# print(f'\n\033[92m<<<================[ Input file split completed ]=================>>>\033[0m')
# print(f'\n\033[92m<<<===================[ 正在转换小分子为.PDB格式 ]===================>>>\033[0m')
# print(f'\n\033[92m<<<=========[ Converting small molecules to .PDB format ]=========>>>\033[0m')
# print(f'\n\033[92m<<<=================[ 已将小分子全部转换为.PDB格式 ]==================>>>\033[0m')
# print(f'\n\033[92m<<<=========[ Small molecules converted to .PDB format. ]=========>>>\033[0m')
# print(f'\n\033[92m<<<=====================[ 正在设置小分子为配体 ]=====================>>>\033[0m')
# print(f'\n\033[92m<<<============[ Setting small molecules as ligands ]=============>>>\033[0m')
# print(f'\n\033[92m<<<====================[ 小分子已全部设置为配体 ]====================>>>\033[0m')
# print(f'\n\033[92m<<<==============[ Small molecules set as ligands ]===============>>>\033[0m')
# print(f'\n\033[92m<<<====================[ 正在验证工作目录完整性 ]====================>>>\033[0m')
# print(f'\n\033[92m<<<=====[ Verifying the integrity of the working directory ]=====>>>\033[0m')
# print(f'\n\033[92m<<<==============[ 正在进行目录补全 > 小分子构象结果目录 ]=============>>>\033[0m')
# print(f'\n\033[92m<<<========[ Performing catalog completion > result_dlg ]========>>>\033[0m')
# print(f'\n\033[92m<<<===============[ 正在进行目录补全 > 对接复合体目录 ]===============>>>\033[0m')
# print(f'\n\033[92m<<<======[ Performing catalog completion > result_complex ]======>>>\033[0m')
# print(f'\n\033[92m<<<===================[ 工作目录完整性验证通过！ ]===================>>>\033[0m')
# print(f'\n\033[92m<<<=====[ Working directory integrity verification passed! ]=====>>>\033[0m')
# print(f'\n\033[92m<<<=================[ 正在初始化结果矩阵与CSV模块 ]==================>>>\033[0m')
# print(f'\n\033[92m<<<=========[ Initializing result matrix and CSV module ]========>>>\033[0m')
# print(f'\n\033[92m<<<===================[ 结果矩阵与CSV模块就绪！ ]===================>>>\033[0m')
# print(f'\n\033[92m<<<========[ The result matrix and CSV module are ready! ]=======>>>\033[0m')
# print(f'\n\033[92m<<<===================[ 正在运行分子对接主程序 ]=====================>>>\033[0m')
# print(f'\n\033[92m<<<===========[ Running the AutoDock-GPU main program ]==========>>>\033[0m')
# print(f'\n\033[92m<<<===================[ 分子对接主程序运行完毕 ]=====================>>>\033[0m')
# print(f'\n\033[92m<<<=======[ Molecular docking main program has completed. ]======>>>\033[0m')
# print(f'\n\033[92m<<<==============[ Prepare_Ligand4程序输出的错误报告: ]=============>>>